### ISSUE TITLE
deviceRegistration.toJsonWithAttestationCert() causes exception

### ISSUE THREAD

**Issue by ukjbrown** [Yubico/java-u2flib-server#22]
When using deviceRegistration.toJsonWithAttestationCert() I receive the following exception;

com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.bouncycastle.math.ec.WNafL2RMultiplier and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: com.yubico.u2f.data.DeviceRegistration["attestationCertificate"]->org.bouncycastle.jcajce.provider.asymmetric.x509.X509CertificateObject["publicKey"]->org.bouncycastle.jcajce.provider.asymmetric.ec.BCECPublicKey["q"]->org.bouncycastle.math.ec.custom.sec.SecP256R1Point["curve"]->org.bouncycastle.math.ec.custom.sec.SecP256R1Curve["multiplier"])

**Comment by dainnilsson** [comment]
This should be resolved by #20, and I'm just about to make a new release of the project (0.16.0) that includes the fix.

**Comment by ukjbrown** [comment]
That's great news - I had just noticed the @JsonIgnore added to the getter. I've implemented a wrapper in my code for now to resolve the issue, but will look forward to the update being available in Maven Central. Cheers.

**Comment by dainnilsson** [comment]
Just released 0.16.0, re-open (or create a new issue) if that doesn't solve the problem.
